meili_search:
  url: '%env(MEILISEARCH_URL)%'          # URL of the Meilisearch server (mandatory)
  api_key: '%env(MEILISEARCH_API_KEY)%'  # API key to access the Meilisearch server (mandatory)
  prefix: ''
  indices:
    - name: food
      class: App\Restaurant\Entity\MenuPosition
      index_if: isActive
      settings:
        searchableAttributes: ['restaurant_name_search', 'food_name_search']
    - name: food
      class: App\Restaurant\Entity\Restaurant
      index_if: isActive
      settings:
        searchableAttributes: ['restaurant_name_search', 'food_name_search']
