sentry:
    dsn: '%env(SENTRY_DSN)%'
    register_error_listener: false
    options:
        traces_sample_rate: 1.0
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'
#        max_request_body_size: medium default value is medium

monolog:
    handlers:
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::ERROR
            hub_id: Sentry\State\HubInterface

services:
    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
                    - Symfony\Component\Security\Core\Exception\AccessDeniedException
    Monolog\Processor\PsrLogMessageProcessor:
        tags: { name: monolog.processor, handler: sentry }
