import './errorHandler';
import '../css/app.scss';
require('react-image-lightbox');
require('react');
require('react-dom');
require('error-stack-parser');
require('react-rating');
require('material-icons');
require('rxjs');
require('react-toastify');
require('bootstrap/dist/js/bootstrap.min');
require('@vaadin/vaadin-upload');
