{
 "title": "ssorder",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Licznik zamówień",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(ssorder_orders_total)" }
   ]
  },
  {
   "title": "Metoda zlozenia zamowienia",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (source) (ssorder_orders_total)",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  {
   "title": "Kody odpowiedzi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (delta(ssorder_response_time_seconds_count[$__range]))",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "500",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ssorder_response_time_seconds_count{status_code=~\"5..\"}[5m]))",
     "legendFormat": "Inc of 5xx in last 5min"
    }
   ]
  }
 ]
}